In [1]:
import numpy as np
import pandas as pd
from MetricMethod import *
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split


In [2]:
iris = load_iris()
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target,
                                                       test_size=0.2, random_state=42)
y_train

array([0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0, 0, 1, 2, 2, 1, 2, 1, 2,
       1, 0, 2, 1, 0, 0, 0, 1, 2, 0, 0, 0, 1, 0, 1, 2, 0, 1, 2, 0, 2, 2,
       1, 1, 2, 1, 0, 1, 2, 0, 0, 1, 1, 0, 2, 0, 0, 1, 1, 2, 1, 2, 2, 1,
       0, 0, 2, 2, 0, 0, 0, 1, 2, 0, 2, 2, 0, 1, 1, 2, 1, 2, 0, 2, 1, 2,
       1, 1, 1, 0, 1, 1, 0, 1, 2, 2, 0, 1, 2, 2, 0, 2, 0, 1, 2, 2, 1, 2,
       1, 1, 2, 2, 0, 1, 2, 0, 1, 2])

In [3]:
knn = KNN(metric="cosine")
knn.fit(X_train, y_train)
predict = knn.predict(X_test)
print(accuracy_score(y_test, predict))

1.0


In [4]:
parzen_window_fixed = ParzenWindowFixedWidth(width=1, method="kdtree")
parzen_window_fixed.fit(X_train, y_train)
predict = parzen_window_fixed.predict(X_test)
print(accuracy_score(y_test, predict))
print(predict)

1.0
[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]


In [5]:
parzen_window_variable = ParzenWindowVariableWidth(countNeighbor=5, method="kdtree")
parzen_window_variable.fit(X_train, y_train)
predict = parzen_window_variable.predict(X_test)
print(accuracy_score(y_test, predict))
print(predict)

1.0
[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]


In [21]:
potential_function = PotentialFunction(width=0.001, metric='cosine', eps=0.1)
potential_function.fit(X_train, y_train)
predict = potential_function.predict(X_test)
print(accuracy_score(y_test, predict))
print(predict)

1.0
[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]
